#define CACHE_L_CB 0
#define CACHE_P_CB 0
#define G_CB_RES_DEST_LEVEL 2
#define INPUT_SIZE_L_1 1024
#define INPUT_SIZE_R_1 1024
#define L_CB_RES_DEST_LEVEL 0
#define L_CB_SIZE_L_1 2
#define L_CB_SIZE_R_1 2
#define L_REDUCTION 1
#define L_WRITE_BACK 1
#define NUM_WG_L_1 16
#define NUM_WG_R_1 8
#define NUM_WI_L_1 4
#define NUM_WI_R_1 1
#define OCL_DIM_L_1 1
#define OCL_DIM_R_1 0
#define P_CB_RES_DEST_LEVEL 0
#define P_CB_SIZE_L_1 8
#define P_CB_SIZE_R_1 64
#define P_WRITE_BACK 0
