#define FILTER_CACHE_LCL 0
#define FILTER_CACHE_PRV 0
#define GLB_1 1
#define GLB_2 1
#define G_CB_RES_DEST_LEVEL 2
#define IMAGES_CACHE_LCL 0
#define IMAGES_CACHE_PRV 0
#define INPUT_SIZE_1 1024
#define INPUT_SIZE_2 1024
#define LCL_1 1
#define LCL_2 8
#define L_CB_RES_DEST_LEVEL 0
#define OUT_CACHE_PRV 0
#define PRV_1 1024
#define PRV_2 2
#define P_CB_RES_DEST_LEVEL 0
#define WG_1 1
#define WG_1_OCL_DIM 1
#define WG_2 1
#define WG_2_OCL_DIM 0
#define WI_1 1
#define WI_1_OCL_DIM 1
#define WI_2 64
#define WI_2_OCL_DIM 0
