#define CACHE_L_CB 0
#define CACHE_P_CB 0
#define G_CB_RES_DEST_LEVEL 2
#define INPUT_SIZE_L_1 8
#define INPUT_SIZE_L_2 8
#define INPUT_SIZE_L_3 8
#define INPUT_SIZE_L_4 8
#define INPUT_SIZE_L_5 8
#define INPUT_SIZE_L_6 8
#define INPUT_SIZE_R_1 8
#define L_CB_RES_DEST_LEVEL 2
#define L_CB_SIZE_L_1 8
#define L_CB_SIZE_L_2 8
#define L_CB_SIZE_L_3 1
#define L_CB_SIZE_L_4 1
#define L_CB_SIZE_L_5 1
#define L_CB_SIZE_L_6 1
#define L_CB_SIZE_R_1 2
#define L_REDUCTION 1
#define L_WRITE_BACK 6
#define NUM_WG_L_1 1
#define NUM_WG_L_2 1
#define NUM_WG_L_3 4
#define NUM_WG_L_4 2
#define NUM_WG_L_5 8
#define NUM_WG_L_6 8
#define NUM_WG_R_1 4
#define NUM_WI_L_1 1
#define NUM_WI_L_2 1
#define NUM_WI_L_3 1
#define NUM_WI_L_4 1
#define NUM_WI_L_5 1
#define NUM_WI_L_6 1
#define NUM_WI_R_1 1
#define OCL_DIM_L_1 2
#define OCL_DIM_L_2 4
#define OCL_DIM_L_3 0
#define OCL_DIM_L_4 1
#define OCL_DIM_L_5 3
#define OCL_DIM_L_6 6
#define OCL_DIM_R_1 5
#define P_CB_RES_DEST_LEVEL 0
#define P_CB_SIZE_L_1 1
#define P_CB_SIZE_L_2 1
#define P_CB_SIZE_L_3 2
#define P_CB_SIZE_L_4 4
#define P_CB_SIZE_L_5 1
#define P_CB_SIZE_L_6 1
#define P_CB_SIZE_R_1 1
#define P_WRITE_BACK 0
