#define CACHE_L_CB 0
#define CACHE_P_CB 0
#define G_CB_RES_DEST_LEVEL 2
#define INPUT_SIZE_L_1 512
#define INPUT_SIZE_L_2 512
#define INPUT_SIZE_R_1 512
#define L_CB_RES_DEST_LEVEL 1
#define L_CB_SIZE_L_1 1
#define L_CB_SIZE_L_2 2
#define L_CB_SIZE_R_1 8
#define L_REDUCTION 1
#define L_WRITE_BACK 2
#define NUM_WG_L_1 128
#define NUM_WG_L_2 4
#define NUM_WG_R_1 16
#define NUM_WI_L_1 1
#define NUM_WI_L_2 2
#define NUM_WI_R_1 4
#define OCL_DIM_L_1 0
#define OCL_DIM_L_2 2
#define OCL_DIM_R_1 1
#define P_CB_RES_DEST_LEVEL 1
#define P_CB_SIZE_L_1 4
#define P_CB_SIZE_L_2 32
#define P_CB_SIZE_R_1 1
#define P_WRITE_BACK 0
